FROM golang:1.20.4-alpine AS builder

RUN apk add build-base
WORKDIR /go/src/github.com/mysteriumnetwork/discovery
COPY go.mod go.sum ./
RUN go mod download

# Compile application
ADD . .
RUN go run mage.go -v buildPricerE2e

FROM alpine:3

# Install packages
RUN apk add --no-cache ca-certificates git

# Install application
COPY --from=builder /go/src/github.com/mysteriumnetwork/discovery/build/pricer /usr/bin/pricer

EXPOSE 8080

CMD ["/usr/bin/pricer"]
