// Package pricer GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package pricer

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/earning-trends": {
            "get": {
                "description": "Country and service demand classifications without pricing values",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Earning trends",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Use countries to omit service-level details",
                        "name": "scope",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/price.EarningTrendsResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/price.PingResponse"
                        }
                    }
                }
            }
        },
        "/prices": {
            "get": {
                "description": "Latest Prices",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Latest Prices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pricingbyservice.LatestPrices"
                        }
                    }
                }
            }
        },
        "/prices/config": {
            "get": {
                "description": "price config",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Price config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pricingbyservice.Config"
                        }
                    }
                }
            },
            "post": {
                "description": "update price config",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "update price config",
                "parameters": [
                    {
                        "description": "config object",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pricingbyservice.Config"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": ""
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/price.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "price.CountryServiceTrend": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "trend": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "price.CountryTrend": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "intensity": {
                    "type": "string"
                },
                "trend": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "price.EarningTrendSummary": {
            "type": "object",
            "properties": {
                "decreasing": {
                    "$ref": "#/definitions/price.TrendSummaryItem"
                },
                "increasing": {
                    "$ref": "#/definitions/price.TrendSummaryItem"
                },
                "stable": {
                    "$ref": "#/definitions/price.TrendSummaryItem"
                }
            }
        },
        "price.EarningTrendsResponse": {
            "type": "object",
            "properties": {
                "countries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/price.CountryTrend"
                    }
                },
                "latest_updates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/price.CountryServiceTrend"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/price.EarningTrendSummary"
                },
                "trends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/price.CountryServiceTrend"
                    }
                }
            }
        },
        "price.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "price.StatusResponse": {
            "type": "object",
            "properties": {
                "cache_ok": {
                    "type": "boolean"
                }
            }
        },
        "price.TrendSummaryItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "share_percentage": {
                    "type": "number"
                }
            }
        },
        "pricingbyservice.Config": {
            "type": "object",
            "properties": {
                "base_prices": {
                    "$ref": "#/definitions/pricingbyservice.PriceByTypeUSD"
                },
                "country_modifiers": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/pricingbyservice.Modifier"
                    }
                },
                "demand_boost": {
                    "$ref": "#/definitions/pricingbyservice.DemandBoostConfig"
                }
            }
        },
        "pricingbyservice.DemandBoostConfig": {
            "type": "object",
            "properties": {
                "countries": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/pricingbyservice.DemandBoostCountryCfg"
                    }
                }
            }
        },
        "pricingbyservice.DemandBoostCountryCfg": {
            "type": "object",
            "properties": {
                "max_bonus": {
                    "type": "number"
                },
                "service_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target_demand_index": {
                    "type": "number"
                }
            }
        },
        "pricingbyservice.LatestPrices": {
            "type": "object",
            "properties": {
                "current_server_time": {
                    "type": "string"
                },
                "current_valid_until": {
                    "type": "string"
                },
                "defaults": {
                    "$ref": "#/definitions/pricingbyservice.PriceHistory"
                },
                "per_country": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/pricingbyservice.PriceHistory"
                    }
                },
                "previous_valid_until": {
                    "type": "string"
                }
            }
        },
        "pricingbyservice.Modifier": {
            "type": "object",
            "properties": {
                "other": {
                    "type": "number"
                },
                "residential": {
                    "type": "number"
                }
            }
        },
        "pricingbyservice.Price": {
            "type": "object",
            "properties": {
                "price_per_gib": {
                    "type": "integer"
                },
                "price_per_gib_human_readable": {
                    "type": "number"
                },
                "price_per_hour": {
                    "type": "integer"
                },
                "price_per_hour_human_readable": {
                    "type": "number"
                }
            }
        },
        "pricingbyservice.PriceByServiceType": {
            "type": "object",
            "properties": {
                "data_transfer": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                },
                "dvpn": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                },
                "monitoring": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                },
                "quic_scraping": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                },
                "runtime": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                },
                "scraping": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                },
                "wireguard": {
                    "$ref": "#/definitions/pricingbyservice.Price"
                }
            }
        },
        "pricingbyservice.PriceByServiceTypeUSD": {
            "type": "object",
            "properties": {
                "data_transfer": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                },
                "dvpn": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                },
                "monitoring": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                },
                "quic_scraping": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                },
                "runtime": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                },
                "scraping": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                },
                "wireguard": {
                    "$ref": "#/definitions/pricingbyservice.PriceUSD"
                }
            }
        },
        "pricingbyservice.PriceByType": {
            "type": "object",
            "properties": {
                "other": {
                    "$ref": "#/definitions/pricingbyservice.PriceByServiceType"
                },
                "residential": {
                    "$ref": "#/definitions/pricingbyservice.PriceByServiceType"
                }
            }
        },
        "pricingbyservice.PriceByTypeUSD": {
            "type": "object",
            "properties": {
                "other": {
                    "$ref": "#/definitions/pricingbyservice.PriceByServiceTypeUSD"
                },
                "residential": {
                    "$ref": "#/definitions/pricingbyservice.PriceByServiceTypeUSD"
                }
            }
        },
        "pricingbyservice.PriceHistory": {
            "type": "object",
            "properties": {
                "current": {
                    "$ref": "#/definitions/pricingbyservice.PriceByType"
                },
                "previous": {
                    "$ref": "#/definitions/pricingbyservice.PriceByType"
                }
            }
        },
        "pricingbyservice.PriceUSD": {
            "type": "object",
            "properties": {
                "price_per_gib_usd": {
                    "type": "number"
                },
                "price_per_hour_usd": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "4.0",
	Host:        "",
	BasePath:    "/api/v4",
	Schemes:     []string{},
	Title:       "Discovery Pricer API",
	Description: "Pricing and earning-trend API for Mysterium Network",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
