version: '2.9'
services:
  discovery:
    build:
      context: ..
      dockerfile: Dockerfile.e2e
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - QUALITY_ORACLE_URL=http://wiremock:8080
      - QUALITY_CACHE_TTL=1s
      - PROPOSALS_CACHE_TTL=0s
      - BADGER_ADDRESS=http://wiremock:8080
      - BROKER_URL=nats://broker
      - LOCATION_ADDRESS=http://wiremock:8080
      - UNIVERSE_JWT_SECRET=suchsecret
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - db
      - broker
      - redis
  discopricer:
    build:
      context: ..
      dockerfile: Dockerfile.e2e.pricer
    depends_on:
      - db
      - wiremock
      - redis
    ports:
      - 8081:8081
    environment:
      - MYSTERIUM_LOG_MODE=json
      - PORT=8081
      - QUALITY_ORACLE_URL=http://wiremock:8004
      - QUALITY_CACHE_TTL=20s
      - BADGER_ADDRESS=http://wiremock:8004
      - SENTINEL_URL=http://wiremock:8004
      - BROKER_URL=nats://broker.mysterium.network
      - UNIVERSE_JWT_SECRET=suchsecret
      - REDIS_ADDRESS=redis:6379
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  db:
    image: postgres:13-alpine
    container_name: discovery_db_e2e
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=discovery
      - POSTGRES_DB=discovery
      - POSTGRES_PASSWORD=discovery

  broker:
    image: nats:1.0.4
    ports:
      - 4222:4222
      - 8222:8222

  wiremock:
    image: rodolpheche/wiremock:2.27.2-alpine
    command: --global-response-templating
    ports:
      - "8004:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings

  dev:
    image: tianon/true
    restart: 'no'
    depends_on:
      - db
      - broker
      - wiremock
      - redis
