// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "Ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proposal.PingResponse"
                        }
                    }
                }
            }
        },
        "/proposals": {
            "get": {
                "description": "List proposals",
                "consumes": [
                    "application/json"
                ],
                "summary": "List proposals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumer country",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "provider_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Service type",
                        "name": "service_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Provider country",
                        "name": "location_country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IP type (residential, datacenter, etc.)",
                        "name": "ip_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Access policy. When empty, returns only public proposals (default). Use 'all' to return all.",
                        "name": "access_policy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Access policy source",
                        "name": "access_policy_source",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum price per GiB. When empty, will not filter by it. Price is set in ethereum wei.",
                        "name": "price_gib_max",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum price per hour. When empty, will not filter by it. Price is set in ethereum wei.",
                        "name": "price_hour_max",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum compatibility. When empty, will not filter by it.",
                        "name": "compatibility_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum compatibility. When empty, will not filter by it.",
                        "name": "compatibility_max",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimal quality threshold. When empty will be defaulted to 0. Quality ranges from [0.0; 3.0]",
                        "name": "quality_min",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Proposal"
                            }
                        }
                    }
                }
            }
        },
        "/proposals-metadata": {
            "get": {
                "description": "List proposals' metadata",
                "consumes": [
                    "application/json"
                ],
                "summary": "List proposals' metadata.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "provider_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Metadata"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "proposal.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "v2.AccessPolicy": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "v2.Contact": {
            "type": "object",
            "properties": {
                "definition": {
                    "type": "object"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v2.Location": {
            "type": "object",
            "properties": {
                "asn": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "continent": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "ip_type": {
                    "type": "string"
                },
                "isp": {
                    "type": "string"
                }
            }
        },
        "v2.Metadata": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "ip_type": {
                    "type": "string"
                },
                "isp": {
                    "type": "string"
                },
                "price_per_gib": {
                    "type": "integer"
                },
                "price_per_hour": {
                    "type": "integer"
                },
                "provider_id": {
                    "type": "string"
                },
                "service_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "whitelist": {
                    "type": "boolean"
                }
            }
        },
        "v2.Price": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "per_gib": {
                    "type": "integer"
                },
                "per_hour": {
                    "type": "integer"
                }
            }
        },
        "v2.Proposal": {
            "type": "object",
            "properties": {
                "access_policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.AccessPolicy"
                    }
                },
                "compatibility": {
                    "type": "integer"
                },
                "contacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.Contact"
                    }
                },
                "format": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "$ref": "#/definitions/v2.Location"
                },
                "price": {
                    "$ref": "#/definitions/v2.Price"
                },
                "provider_id": {
                    "type": "string"
                },
                "quality": {
                    "$ref": "#/definitions/v2.Quality"
                },
                "service_type": {
                    "type": "string"
                }
            }
        },
        "v2.Quality": {
            "type": "object",
            "properties": {
                "bandwidth": {
                    "description": "Bandwidth in Mbps.",
                    "type": "number"
                },
                "latency": {
                    "description": "Latency in ms.",
                    "type": "number"
                },
                "quality": {
                    "description": "Quality valuation from the oracle.",
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "3.0",
	Host:        "",
	BasePath:    "/api/v3",
	Schemes:     []string{},
	Title:       "Discovery API",
	Description: "Discovery API for Mysterium Network",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
