basePath: /api/v3
definitions:
  health.PingResponse:
    properties:
      message:
        type: string
    type: object
  health.StatusResponse:
    properties:
      cache_ok:
        type: boolean
    type: object
  pricing.Config:
    properties:
      base_prices:
        $ref: '#/definitions/pricing.PriceByTypeUSD'
      country_modifiers:
        additionalProperties:
          $ref: '#/definitions/pricing.Modifier'
        type: object
    type: object
  pricing.LatestPrices:
    properties:
      current_server_time:
        type: string
      current_valid_until:
        type: string
      defaults:
        $ref: '#/definitions/pricing.PriceHistory'
      per_country:
        additionalProperties:
          $ref: '#/definitions/pricing.PriceHistory'
        type: object
      previous_valid_until:
        type: string
    type: object
  pricing.Modifier:
    properties:
      other:
        type: number
      residential:
        type: number
    type: object
  pricing.Price:
    properties:
      price_per_gib:
        type: integer
      price_per_gib_human_readable:
        type: number
      price_per_hour:
        type: integer
      price_per_hour_human_readable:
        type: number
    type: object
  pricing.PriceByType:
    properties:
      other:
        $ref: '#/definitions/pricing.Price'
      residential:
        $ref: '#/definitions/pricing.Price'
    type: object
  pricing.PriceByTypeUSD:
    properties:
      other:
        $ref: '#/definitions/pricing.PriceUSD'
      residential:
        $ref: '#/definitions/pricing.PriceUSD'
    type: object
  pricing.PriceHistory:
    properties:
      current:
        $ref: '#/definitions/pricing.PriceByType'
      previous:
        $ref: '#/definitions/pricing.PriceByType'
    type: object
  pricing.PriceUSD:
    properties:
      price_per_gib_usd:
        type: number
      price_per_hour_usd:
        type: number
    type: object
  v3.AccessPolicy:
    properties:
      id:
        type: string
      source:
        type: string
    type: object
  v3.Contact:
    properties:
      definition:
        type: object
      type:
        type: string
    type: object
  v3.Location:
    properties:
      asn:
        type: integer
      city:
        type: string
      continent:
        type: string
      country:
        type: string
      ip_type:
        type: string
      isp:
        type: string
    type: object
  v3.Metadata:
    properties:
      country:
        type: string
      ip_type:
        type: string
      isp:
        type: string
      monitoring_failed:
        type: boolean
      provider_id:
        type: string
      service_type:
        type: string
      updated_at:
        type: string
      whitelist:
        type: boolean
    type: object
  v3.Proposal:
    properties:
      access_policies:
        items:
          $ref: '#/definitions/v3.AccessPolicy'
        type: array
      compatibility:
        type: integer
      contacts:
        items:
          $ref: '#/definitions/v3.Contact'
        type: array
      format:
        type: string
      id:
        type: integer
      location:
        $ref: '#/definitions/v3.Location'
      provider_id:
        type: string
      quality:
        $ref: '#/definitions/v3.Quality'
      service_type:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  v3.Quality:
    properties:
      bandwidth:
        description: Bandwidth in Mbps.
        type: number
      latency:
        description: Latency in ms.
        type: number
      monitoring_failed:
        description: MonitoringFailed did monitoring agent succeed to connect to the
          node.
        type: boolean
      quality:
        description: Quality valuation from the oracle.
        type: number
      uptime:
        description: Uptime in hours per day
        type: number
    type: object
info:
  contact: {}
  description: Discovery API for Mysterium Network
  title: Discovery API
  version: "3.0"
paths:
  /countries:
    get:
      consumes:
      - application/json
      description: List number of providers in each country
      parameters:
      - description: Consumer country
        in: query
        name: from
        type: string
      - description: Provider ID
        in: query
        name: provider_id
        type: string
      - description: Service type
        in: query
        name: service_type
        type: string
      - description: Provider country
        in: query
        name: location_country
        type: string
      - description: IP type (residential, datacenter, etc.)
        in: query
        name: ip_type
        type: string
      - description: Access policy. When empty, returns only public proposals (default).
          Use 'all' to return all.
        in: query
        name: access_policy
        type: string
      - description: Access policy source
        in: query
        name: access_policy_source
        type: string
      - description: Minimum compatibility. When empty, will not filter by it.
        in: query
        name: compatibility_min
        type: number
      - description: Maximum compatibility. When empty, will not filter by it.
        in: query
        name: compatibility_max
        type: number
      - description: Minimal quality threshold. When empty will be defaulted to 0.
          Quality ranges from [0.0; 3.0]
        in: query
        name: quality_min
        type: number
      responses: {}
      summary: List number of providers in each country
      tags:
      - countries
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.PingResponse'
      summary: Ping
      tags:
      - system
  /prices:
    get:
      description: Latest Prices
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pricing.LatestPrices'
            type: array
      summary: Latest Prices
      tags:
      - prices
  /prices/config:
    get:
      description: price config
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pricing.Config'
            type: array
      summary: Price config
      tags:
      - prices
    post:
      description: update price config
      parameters:
      - description: config object
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/pricing.Config'
      responses:
        "202":
          description: ""
      summary: update price config
      tags:
      - prices
  /proposals:
    get:
      consumes:
      - application/json
      description: List proposals
      parameters:
      - description: Consumer country
        in: query
        name: from
        type: string
      - description: Provider ID
        in: query
        name: provider_id
        type: string
      - description: Service type
        in: query
        name: service_type
        type: string
      - description: Provider country
        in: query
        name: location_country
        type: string
      - description: IP type (residential, datacenter, etc.)
        in: query
        name: ip_type
        type: string
      - description: Access policy. When empty, returns only public proposals (default).
          Use 'all' to return all.
        in: query
        name: access_policy
        type: string
      - description: Access policy source
        in: query
        name: access_policy_source
        type: string
      - description: Minimum compatibility. When empty, will not filter by it.
        in: query
        name: compatibility_min
        type: number
      - description: Maximum compatibility. When empty, will not filter by it.
        in: query
        name: compatibility_max
        type: number
      - description: Minimal quality threshold. When empty will be defaulted to 0.
          Quality ranges from [0.0; 3.0]
        in: query
        name: quality_min
        type: number
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v3.Proposal'
            type: array
      summary: List proposals
      tags:
      - proposals
  /proposals-metadata:
    get:
      consumes:
      - application/json
      description: List proposals' metadata
      parameters:
      - description: Provider ID
        in: query
        name: provider_id
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v3.Metadata'
            type: array
      summary: List proposals' metadata.
  /status:
    get:
      consumes:
      - application/json
      description: Status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.StatusResponse'
      summary: Status
      tags:
      - system
swagger: "2.0"
